### ISSUE TITLE
JSON export/import function

### ISSUE THREAD

**Issue by jsgm** [ostafen/clover#16]
Taking account that Clover is looking forward to implement different types of storage engines and is mainly used for small and embedded databases, adding the possibility to easily export and import your data to JSON independently of the engine used, would be really helpful for working with test data, backing up, etc.

However, there are a few problems:
- How to handle the conversion specially for bigger databases. Possible bottlenecks?
- Use one just single file or multiple files. Maybe both options?

**Comment by ostafen** [comment]
Hi, jsgm, first of all thank you for the nice suggestion.

> How to handle the conversion specially for bigger databases. Possible bottlenecks?

Regarding this point, I think that conversion should be performed in a cleaver way than simply calling json.Marshal on a document slice. I think that, in order to serialize large collections efficiently, documents should be progressively serialized and written to the exported file.

> Use one just single file or multiple files. Maybe both options?

I think that it is fine to start by implementing a db.ExportCollection(collectionName, exportPath) function, which allow to export a single collection in a json file with the same name of the collection itself.
Then, by using this function, we could also implement an additional ExportDatabase(folderPath) function, exporting each collection inside a folder. 
In the last case, we could also reason about an option for exporting the entire database in a single file (but this could also be added in a second step).

**Comment by ostafen** [comment]
@jsgm Just to plan my activities, are you going to work on this? If you are busy, I'll put this on my todo list :=)

**Comment by jsgm** [comment]
> @jsgm Just to plan my activities, are you going to work on this? If you are busy, I'll put this on my todo list :=)

Sorry for the delay! A bit busy this week, feel free to put it in your todo list. In any case still looking forward to further contributions 😃

**Comment by ostafen** [comment]
There is no rush, if you are interested in this ;=)

**Comment by jsgm** [comment]
> There is no rush, if you are interested in this ;=)

Thanks for your patient. If there's no rush I can definitely go with this. Starting today!
